"""added username field to Users

Revision ID: 220a19797ada
Revises: e0c3948dcbdb
Create Date: 2022-05-02 14:12:51.585028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220a19797ada'
down_revision = 'e0c3948dcbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
