"""password field

Revision ID: 9b38221ad947
Revises: c70ad6fc9190
Create Date: 2022-05-01 18:03:41.432100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b38221ad947'
down_revision = 'c70ad6fc9190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_model', sa.Column('password_hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_model', 'password_hash')
    # ### end Alembic commands ###
